<a href="https://colab.research.google.com/github/dddickson07/data-science-coding/blob/main/numpycrashcourse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Introduction

Numpy is used as preferred to lists because it is a lot **faster.**

Example:
5 --> 0000101 in Binary --> 00000 0000 0000 00000101 Int 32 in Numpy ---> Size, reference count, object type, etc --> list. A single integer requires a lot more space!

So...
- faster to read less bytes of memory
- won't need to type check
- Numpy uses continuous memory so all 8 blocks of memory are next to eachother
  - SIMD Vector Processing
  - Effective Cache Utilization


## Applications of NumPy
Useful in Mathematics (MATLAB Replacement), plotting (Matplotlib), Pandas, and Machine Learning!







In [21]:
# intiaalizaing an array
import numpy as np

a = np.array([1,2,3])
print(a)

b = np.array([[9.0,8.0,0.8],[6.0,5.0,4.0]])

print(a.ndim)

a.shape

b.shape

a.itemsize

b.itemsize

##changing specific elements, rows, columns

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

print(a)

a.shape

a[0,5]

##specific row
a[0, :]

#specific column
a[: , 2]

#fancy stuff
a[0,1:-1:2]

#change an element
a[1,5] = 20

a[:,2] = [1,2]
print(a)


#specific example

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])


print(b)
print(b[0,1,1])

[1 2 3]
1
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4


Initializing Different Types of Array

In [48]:
np.zeros((2,3,3))

np.ones((4,2,2))

#anyother number

np.full((2,2),99)

np.full_like(a,4)

#random decimal numbers

np.random.rand(4,2,3)

#random. integers

np.random.randint(-4,8, size = (3,3))

#The identity matrix

np.identity(5)

#repeat array

arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis = 0)

In [52]:
#Challenge Problem

output = np.ones((5,5))
print(output)
output[1:4,1:4] = 0
output[2,2] = 9
print(output)
# or

z = np.zeros((3,3))
z[1,1] = 9
print(z)
output[1:-1,1:-1] = z

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Mathematics:
- Can perform all math operations

In [57]:
a = np.array([1,2,3,4])
print(a)

a + 2
a+= 2
a / 2

np.cos(a)

[1 2 3 4]


array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

Linear Algebra with Numpy

In [63]:
a = np.ones((2,3))

print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

c = np.identity(3)
np.linalg.det(c)

np.linalg.inv(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Statistics with Numpy

In [66]:
stats = np.array([[1,2,3],[4,5,6]])
stats

np.min(stats,axis=1)


array([1, 4])

Reorgannizing Arrays

In [72]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((4,2))
print(after)

#vertical stack
np.vstack((before,before))

#loading data

np.genfromtxt()

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])